Add item requests
mikhaylenko-sd/java-shareit pull request #3
Opened 2023-03-26 00:15 UTC by mikhaylenko-sd

sprint 15 - add item-requests logic and tests

2023-03-26 17:19 UTC, Fleaman777 requested changes

2023-03-26 17:19 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        itemRequestDtos.forEach(this::setRequestItems);
хороший стрим, но можно его немного проапдейтить, 
вместо того, что бы его собирать а потом вызывать метод foreach, 

можно вернуть результат стрима, без просечивания его в переменную itemRequestDtos, а вместо метода foreach использовать метод peek 

аналагично в др похожих местах

2023-03-26 17:19 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void test() throws Exception {
хорош было бы уточнить, что именно это за тест)

2023-03-26 17:19 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        UserDto newUserDto = userService.create(generateUser());
эту инициализацию можно было бы вынести в метод с аннотацией @BeforeEach

2023-03-26 23:12 UTC, mikhaylenko-sd commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        itemRequestDtos.forEach(this::setRequestItems);
не знала про этот метод, спасибо)

2023-03-27 17:59 UTC, Fleaman777 approved these changes

2023-04-04 19:14 UTC, merged