sprint 16
mikhaylenko-sd/java-shareit pull request #4
Opened 2023-04-11 00:45 UTC by mikhaylenko-sd

2023-04-11 20:14 UTC, Fleaman777 requested changes

2023-04-11 20:14 UTC, Fleaman777 commented on docker-compose.yml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к Dockerfile

2023-04-11 20:14 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(value = "from", required = false, defaultValue = "0") int from,
если значение параметра value совпадает с названием аргумента метода, то явно параметр можно не указывать

2023-04-11 20:14 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
здорово, правильная конструкция для просечивания энв переменных,
еще можно ее немного дополнить
spring.datasource.username=${POSTGRES_USER:postgres}

через двоеточие указывается значение, которое будет использоваться по умолчанию, если энв переменная не будет просечена

2023-04-12 11:56 UTC, mikhaylenko-sd commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
спасибо! как раз не знала, как избежать закомментированных строк

2023-04-12 18:31 UTC, Fleaman777 approved these changes

2023-04-12 22:56 UTC, merged